# Generated by Django 5.0.4 on 2024-05-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rollno', models.IntegerField()),
                ('course', models.CharField(choices=[('IT', 'InformationTechnology'), ('CE', 'Computer Engineering')], max_length=2)),
            ],
        ),
    ]
