# Generated by Django 5.0.4 on 2024-05-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('IT', 'InformationTechnology'), ('CE', 'Computer Engineering')], default='InformationTechnology', max_length=2),
        ),
    ]
